// <auto-generated />
using System;
using IDensity.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IDensity.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230410075400_Add_Meas_ResultLogs")]
    partial class Add_Meas_ResultLogs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.29");

            modelBuilder.Entity("IDensity.DataAccess.Models.MeasResultLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("AvgValue1")
                        .HasColumnType("REAL");

                    b.Property<float>("AvgValue2")
                        .HasColumnType("REAL");

                    b.Property<float>("CurValue1")
                        .HasColumnType("REAL");

                    b.Property<float>("CurValue2")
                        .HasColumnType("REAL");

                    b.Property<float>("Current1")
                        .HasColumnType("REAL");

                    b.Property<float>("Current2")
                        .HasColumnType("REAL");

                    b.Property<float>("HvValue1")
                        .HasColumnType("REAL");

                    b.Property<float>("Pulses")
                        .HasColumnType("REAL");

                    b.Property<float>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MeasResultLogs");
                });

            modelBuilder.Entity("IDensity.DataAccess.Models.MeasUnit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceType")
                        .HasColumnType("INTEGER");

                    b.Property<float>("K")
                        .HasColumnType("REAL");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<float>("Offset")
                        .HasColumnType("REAL");

                    b.Property<bool>("UserCantDelete")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MeasUnits");
                });

            modelBuilder.Entity("IDensity.DataAccess.Models.MeasUnitMemory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("MeasUnitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MeasUnitMemories");
                });
#pragma warning restore 612, 618
        }
    }
}
